SRC_URI += "file://patches/ath/070-ath_common_config.patch \
		  file://patches/ath/400-ath_move_debug_code.patch \
		  file://patches/ath/402-ath_regd_optional.patch \
		  file://patches/ath/403-world_regd_fixup.patch \
		  file://patches/ath/404-regd_no_assoc_hints.patch \
		  file://patches/ath/405-ath_regd_us.patch \
		  file://patches/ath/406-ath_relax_default_regd.patch \
		  file://patches/ath/431-add_platform_eeprom_support_to_ath5k.patch \
		  "
