SRC_URI += "file://patches/ath10k/080-ath10k_thermal_config.patch \
		file://patches/ath10k/120-ath10k-fetch-calibration-data-via-nvmem-subsystem.patch \
		file://patches/ath10k/921-ath10k_init_devices_synchronously.patch \
		file://patches/ath10k/930-ath10k_add_tpt_led_trigger.patch \
		file://patches/ath10k/974-ath10k_add-LED-and-GPIO-controlling-support-for-various-chipsets.patch \
		file://patches/ath10k/975-ath10k-use-tpt-trigger-by-default.patch \
		file://patches/ath10k/981-ath10k-adjust-tx-power-reduction-for-US-regulatory-d.patch \
		file://patches/ath10k/984-ath10k-Try-to-get-mac-address-from-dts.patch \
		"
