SRC_URI += "file://patches/ath11k/0001-v5.16-ath11k-qmi-avoid-error-messages-when-dma-allocation-.patch \
		file://patches/ath11k/0002-v5.16-ath11k-use-hw_params-to-access-board_size-and-cal_of.patch \
		file://patches/ath11k/100-ath11k-load-appropriate-board-data-from-board-id.patch \
		file://patches/ath11k/101-ath11k-add-support-for-channel-rx-tx-time-in-survey-dump.patch \
		file://patches/ath11k/900-ath11k-Disable-coldboot-calibration-for-IPQ8074.patch \
		file://patches/ath11k/901-ath11k-add-support-for-512MB-memory-profile.patch \
		"
