SRC_URI += "file://patches/brcm/040-brcmutil_option.patch \
		file://patches/brcm/810-b43-gpio-mask-module-option.patch \
		file://patches/brcm/811-b43_no_pio.patch \
		file://patches/brcm/812-b43-add-antenna-control.patch \
		file://patches/brcm/813-b43-reduce-number-of-RX-slots.patch \
		file://patches/brcm/814-b43-only-use-gpio-0-1-for-led.patch \
		file://patches/brcm/815-b43-always-take-overlapping-devs.patch \
		file://patches/brcm/850-brcmsmac-remove-extra-regulation-restriction.patch \
		file://patches/brcm/860-brcmfmac-register-wiphy-s-during-module_init.patch \
		file://patches/brcm/861-brcmfmac-workaround-bug-with-some-inconsistent-BSSes.patch \
		file://patches/brcm/862-brcmfmac-Disable-power-management.patch \
		file://patches/brcm/863-brcmfmac-add-in-driver-tables-with-country-codes.patch \
		file://patches/brcm/864-brcmfmac-do-not-use-internal-roaming-engine-by-default.patch \
		file://patches/brcm/998-survey.patch \
		"
