SRC_URI += "file://patches/build/000-fix_kconfig.patch \
		file://patches/build/001-fix_build.patch \
		file://patches/build/002-change_allconfig.patch \
		file://patches/build/003-remove_bogus_modparams.patch \
		file://patches/build/012-kernel_build_check.patch \
		file://patches/build/015-ipw200-mtu.patch \
		file://patches/build/050-lib80211_option.patch \
		file://patches/build/060-no_local_ssb_bcma.patch \
		"
