SRC_URI += "file://patches/rt2x00/002-rt2x00-define-RF5592-in-init_eeprom-routine.patch \
		file://patches/rt2x00/100-rt2x00_options.patch \
		file://patches/rt2x00/501-rt2x00-allow-to-build-rt2800soc-module-for-RT3883.patch \
		file://patches/rt2x00/601-rt2x00-introduce-rt2x00_platform_h.patch \
		file://patches/rt2x00/602-rt2x00-introduce-rt2x00eeprom.patch \
		file://patches/rt2x00/603-rt2x00-of_load_eeprom_filename.patch \
		file://patches/rt2x00/604-rt2x00-load-eeprom-on-SoC-from-a-mtd-device-defines-.patch \
		file://patches/rt2x00/606-rt2x00-allow_disabling_bands_through_platform_data.patch \
		file://patches/rt2x00/607-rt2x00-add_platform_data_mac_addr.patch \
		file://patches/rt2x00/608-rt2x00-allow_disabling_bands_through_dts.patch \
		file://patches/rt2x00/609-rt2x00-make-wmac-loadable-via-OF-on-rt288x-305x-SoC.patch \
		file://patches/rt2x00/610-rt2x00-change-led-polarity-from-OF.patch \
		file://patches/rt2x00/611-rt2x00-add-AP+STA-support.patch \
		file://patches/rt2x00/612-rt2x00-led-tpt-trigger-support.patch \
		file://patches/rt2x00/650-rt2x00-add-support-for-external-PA-on-MT7620.patch \
		file://patches/rt2x00/982-rt2x00-add-rf-self-txdc-calibration.patch \
		file://patches/rt2x00/983-rt2x00-add-r-calibration.patch \
		file://patches/rt2x00/984-rt2x00-add-rxdcoc-calibration.patch \
		file://patches/rt2x00/985-rt2x00-add-rxiq-calibration.patch \
		file://patches/rt2x00/986-rt2x00-add-TX-LOFT-calibration.patch \
		file://patches/rt2x00/990-rt2x00-mt7620-introduce-accessors-for-CHIP_VER-register.patch \
		file://patches/rt2x00/991-rt2x00-mt7620-differentiate-based-on-SoC-CHIP_VER.patch \
		"