SRC_URI += "file://patches/subsys/110-mac80211_keep_keys_on_stop_ap.patch \
		file://patches/subsys/120-cfg80211_allow_perm_addr_change.patch \
		file://patches/subsys/150-disable_addr_notifier.patch \
		file://patches/subsys/210-ap_scan.patch \
		file://patches/subsys/304-mac80211-sta-randomize-BA-session-dialog-token-alloc.patch \
		file://patches/subsys/321-mac80211_hwsim-make-6-GHz-channels-usable.patch \
		file://patches/subsys/353-mac80211-minstrel_ht-fix-MINSTREL_FRAC-macro.patch \
		file://patches/subsys/354-mac80211-minstrel_ht-reduce-fluctuations-in-rate-pro.patch \
		file://patches/subsys/355-mac80211-minstrel_ht-rework-rate-downgrade-code-and-.patch \
		file://patches/subsys/400-allow-ibss-mixed.patch \
		file://patches/subsys/500-mac80211_configure_antenna_gain.patch \
		file://patches/subsys/782-net-next-1-of-net-pass-the-dst-buffer-to-of_get_mac_address.patch \
		"
