SRC_URI += "file://patches/subsys/0001-v5.16-ieee80211-Add-new-A-MPDU-factor-macro-for-HE-6-GHz-p.patch \
		file://patches/subsys/110-mac80211_keep_keys_on_stop_ap.patch \
		file://patches/subsys/120-cfg80211_allow_perm_addr_change.patch \
		file://patches/subsys/150-disable_addr_notifier.patch \
		file://patches/subsys/210-ap_scan.patch \
		file://patches/subsys/301-mac80211-fix-rate-control-for-retransmitted-frames.patch \
		file://patches/subsys/304-mac80211-sta-randomize-BA-session-dialog-token-alloc.patch \
		file://patches/subsys/305-mac80211-fix-regression-in-SSN-handling-of-addba-tx.patch \
		file://patches/subsys/306-mac80211-set-up-the-fwd_skb-dev-for-mesh-forwarding.patch \
		file://patches/subsys/309-mac80211-send-ADDBA-requests-using-the-tid-queue-of-.patch \
		file://patches/subsys/310-mac80211-agg-tx-don-t-schedule_and_wake_txq-under-st.patch \
		file://patches/subsys/321-mac80211_hwsim-make-6-GHz-channels-usable.patch \
		file://patches/subsys/353-mac80211-minstrel_ht-fix-MINSTREL_FRAC-macro.patch \
		file://patches/subsys/354-mac80211-minstrel_ht-reduce-fluctuations-in-rate-pro.patch \
		file://patches/subsys/355-mac80211-minstrel_ht-rework-rate-downgrade-code-and-.patch \
		file://patches/subsys/400-allow-ibss-mixed.patch \
		file://patches/subsys/500-mac80211_configure_antenna_gain.patch \
		file://patches/subsys/782-net-next-1-of-net-pass-the-dst-buffer-to-of_get_mac_address.patch \
		"
